import type { Lead } from "../types";

export const generatedLeadPool: Lead[] = [
  {
    id: "1",
    name: "Melissa Grant",
    jobTitle: "Growth Director",
    role: "Director",
    function: "Marketing & Growth",
    company: "Aster & Co.",
    industry: "Marketing & Agency",
    companySize: "50-100",
    country: "United Kingdom",
    state: "Greater London",
    city: "London",
    location: "London, UK",
    companyHeadquarters: "London, United Kingdom",
    email: "m.grant@asterco.co.uk",
    verificationTag: "Email verified",
    matchReason: "Agency growth leader with a relevant expansion signal.",
    matchScore: 98,
    status: "Discovered",
  },
  {
    id: "2",
    name: "Omar Siddiqui",
    jobTitle: "Founder & CEO",
    role: "Executive",
    function: "Executive Leadership",
    company: "Formstack Labs",
    industry: "Enterprise SaaS",
    companySize: "100-250",
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    location: "Dubai, UAE",
    companyHeadquarters: "Dubai, United Arab Emirates",
    email: "omar@formstacklabs.io",
    verificationTag: "Enriched",
    matchReason: "Founder-led team seeking qualified sales conversations.",
    matchScore: 96,
    status: "Discovered",
  },
  {
    id: "3",
    name: "Sana Ahmed",
    jobTitle: "Managing Partner",
    role: "Executive",
    function: "Executive Leadership",
    company: "Northstar Talent",
    industry: "Staffing & Recruiting",
    companySize: "10-50",
    country: "Pakistan",
    state: "Sindh",
    city: "Karachi",
    location: "Karachi, PK",
    companyHeadquarters: "Karachi, Pakistan",
    email: "sana@northstartalent.com",
    verificationTag: "Email verified",
    matchReason: "Recruitment decision-maker with high-fit service motion.",
    matchScore: 94,
    status: "Discovered",
  },
  {
    id: "4",
    name: "James Chen",
    jobTitle: "Head of Partnerships",
    role: "Director",
    function: "Partnerships & Alliances",
    company: "Kindred Studio",
    industry: "Marketing & Agency",
    companySize: "50-100",
    country: "Singapore",
    state: "Central Region",
    city: "Singapore",
    location: "Singapore",
    companyHeadquarters: "Singapore, Singapore",
    email: "james.chen@kindredstudio.sg",
    verificationTag: "Review contact",
    matchReason: "Partnership remit aligns with expansion and pipeline goals.",
    matchScore: 92,
    status: "Discovered",
  },
  {
    id: "5",
    name: "Sarah Jenkins",
    jobTitle: "VP of Demand Generation",
    role: "Executive",
    function: "Marketing & Growth",
    company: "CloudScale Inc.",
    industry: "Enterprise SaaS",
    companySize: "250-500",
    country: "United States",
    state: "California",
    city: "San Francisco",
    location: "San Francisco, CA, USA",
    companyHeadquarters: "San Francisco, United States",
    email: "s.jenkins@cloudscale.io",
    verificationTag: "Email verified",
    matchReason: "Scaling outbound revenue with deliverability safeguards.",
    matchScore: 95,
    status: "Discovered",
  },
  {
    id: "6",
    name: "Elena Rostova",
    jobTitle: "Head of Sales Operations",
    role: "Director",
    function: "Sales & Revenue",
    company: "Nexlify Bio",
    industry: "Healthcare Technology",
    companySize: "100-250",
    country: "Germany",
    state: "Berlin",
    city: "Berlin",
    location: "Berlin, Germany",
    companyHeadquarters: "Berlin, Germany",
    email: "elena@nexlifybio.de",
    verificationTag: "Enriched",
    matchReason: "Leading revenue operations and automated lead workflows.",
    matchScore: 90,
    status: "Discovered",
  },
  {
    id: "7",
    name: "David K. Chen",
    jobTitle: "Director of Growth Marketing",
    role: "Director",
    function: "Marketing & Growth",
    company: "ApexLogistics AI",
    industry: "Supply Chain AI",
    companySize: "100-250",
    country: "United States",
    state: "Texas",
    city: "Austin",
    location: "Austin, TX, USA",
    companyHeadquarters: "Austin, United States",
    email: "dchen@apexlogistics.ai",
    verificationTag: "Email verified",
    matchReason: "Director evaluating deliverability and automated prospecting.",
    matchScore: 91,
    status: "Discovered",
  },
  {
    id: "8",
    name: "Amara Okafor",
    jobTitle: "VP of Strategic Alliances",
    role: "Executive",
    function: "Partnerships & Alliances",
    company: "SaaSBridge Global",
    industry: "Cloud Infrastructure",
    companySize: "500-1000",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    location: "Toronto, ON, Canada",
    companyHeadquarters: "Toronto, Canada",
    email: "amara.o@saasbridge.com",
    verificationTag: "Email verified",
    matchReason: "Scaling ecosystem partnerships with enterprise SaaS buyers.",
    matchScore: 89,
    status: "Discovered",
  },
  {
    id: "9",
    name: "Marcus Vance",
    jobTitle: "Managing Director, Commercial",
    role: "Executive",
    function: "Sales & Revenue",
    company: "Vanguard Growth Partners",
    industry: "Marketing & Agency",
    companySize: "250-500",
    country: "United States",
    state: "New York",
    city: "New York",
    location: "New York, NY, USA",
    companyHeadquarters: "New York, United States",
    email: "m.vance@vanguardgp.com",
    verificationTag: "Review contact",
    matchReason: "Commercial agency leader actively hiring outbound sales SDRs.",
    matchScore: 88,
    status: "Discovered",
  },
  {
    id: "10",
    name: "Sophie Leclerc",
    jobTitle: "VP Revenue Operations",
    role: "Executive",
    function: "Sales & Revenue",
    company: "Luminary AI",
    industry: "Enterprise SaaS",
    companySize: "100-250",
    country: "United States",
    state: "California",
    city: "San Francisco",
    location: "San Francisco, CA, USA",
    companyHeadquarters: "San Francisco, United States",
    email: "sleclerc@luminaryai.com",
    verificationTag: "Email verified",
    matchReason: "Focusing on sales inbox deliverability and deliverability guards.",
    matchScore: 97,
    status: "Discovered",
  },
];

export function leadDomain(lead: Lead) {
  return lead.domain || lead.email.split("@")[1] || "";
}

export function getLeadFunction(lead: Lead): string {
  if (lead.function) return lead.function;
  const title = (lead.jobTitle || "").toLowerCase();
  if (/growth|demand|marketing|brand|seo|content/.test(title)) return "Marketing & Growth";
  if (/sales|revenue|revops|account|sdr|bdr|commercial/.test(title)) return "Sales & Revenue";
  if (/founder|ceo|managing partner|owner|president|co-founder/.test(title)) return "Executive Leadership";
  if (/partnership|alliances|business development|channel/.test(title)) return "Partnerships & Alliances";
  if (/operations|ops|logistics|supply chain/.test(title)) return "Operations";
  if (/engineering|product|cto|cpo|developer|tech/.test(title)) return "Engineering & Product";
  if (/talent|recruit|people|hr/.test(title)) return "HR & Recruiting";
  return "General Management";
}

export function getLeadHeadquarters(lead: Lead): string {
  if (lead.companyHeadquarters) return lead.companyHeadquarters;
  if (lead.city && lead.country) return `${lead.city}, ${lead.country}`;
  if (lead.location) return lead.location;
  if (lead.country) return lead.country;
  return "Global";
}

export function uniqueSorted(values: string[]) {
  return Array.from(new Set(values.filter(Boolean))).sort((a, b) => a.localeCompare(b));
}
