import type { Lead } from "../types";

export const generatedLeadPool: Lead[] = [
  {
    id: "1",
    name: "Melissa Grant",
    jobTitle: "Growth Director",
    role: "Director",
    company: "Aster & Co.",
    industry: "Marketing & Agency",
    companySize: "50-100",
    country: "United Kingdom",
    state: "Greater London",
    city: "London",
    location: "London, UK",
    email: "m.grant@asterco.co.uk",
    verificationTag: "Email verified",
    matchReason: "Agency growth leader with a relevant expansion signal.",
    matchScore: 98,
    status: "Discovered",
  },
  {
    id: "2",
    name: "Omar Siddiqui",
    jobTitle: "Founder & CEO",
    role: "Executive",
    company: "Formstack Labs",
    industry: "Enterprise SaaS",
    companySize: "100-250",
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    location: "Dubai, UAE",
    email: "omar@formstacklabs.io",
    verificationTag: "Enriched",
    matchReason: "Founder-led team seeking qualified sales conversations.",
    matchScore: 96,
    status: "Discovered",
  },
  {
    id: "3",
    name: "Sana Ahmed",
    jobTitle: "Managing Partner",
    role: "Executive",
    company: "Northstar Talent",
    industry: "Staffing & Recruiting",
    companySize: "10-50",
    country: "Pakistan",
    state: "Sindh",
    city: "Karachi",
    location: "Karachi, PK",
    email: "sana@northstartalent.com",
    verificationTag: "Email verified",
    matchReason: "Recruitment decision-maker with high-fit service motion.",
    matchScore: 94,
    status: "Discovered",
  },
  {
    id: "4",
    name: "James Chen",
    jobTitle: "Head of Partnerships",
    role: "Director",
    company: "Kindred Studio",
    industry: "Marketing & Agency",
    companySize: "50-100",
    country: "Singapore",
    state: "Central Region",
    city: "Singapore",
    location: "Singapore",
    email: "james.chen@kindredstudio.sg",
    verificationTag: "Review contact",
    matchReason: "Partnership remit aligns with expansion and pipeline goals.",
    matchScore: 92,
    status: "Discovered",
  },
  {
    id: "5",
    name: "Sarah Jenkins",
    jobTitle: "VP of Demand Generation",
    role: "Executive",
    company: "CloudScale Inc.",
    industry: "Enterprise SaaS",
    companySize: "250-500",
    country: "United States",
    state: "California",
    city: "San Francisco",
    location: "San Francisco, CA, USA",
    email: "s.jenkins@cloudscale.io",
    verificationTag: "Email verified",
    matchReason: "Scaling outbound revenue with deliverability safeguards.",
    matchScore: 95,
    status: "Discovered",
  },
  {
    id: "6",
    name: "Elena Rostova",
    jobTitle: "Head of Sales Operations",
    role: "Director",
    company: "Nexlify Bio",
    industry: "Healthcare Technology",
    companySize: "100-250",
    country: "Germany",
    state: "Berlin",
    city: "Berlin",
    location: "Berlin, Germany",
    email: "elena@nexlifybio.de",
    verificationTag: "Enriched",
    matchReason: "Leading revenue operations and automated lead workflows.",
    matchScore: 90,
    status: "Discovered",
  },
  {
    id: "7",
    name: "David K. Chen",
    jobTitle: "Director of Growth Marketing",
    role: "Director",
    company: "ApexLogistics AI",
    industry: "Supply Chain AI",
    companySize: "100-250",
    country: "United States",
    state: "Texas",
    city: "Austin",
    location: "Austin, TX, USA",
    email: "dchen@apexlogistics.ai",
    verificationTag: "Email verified",
    matchReason: "Director evaluating deliverability and automated prospecting.",
    matchScore: 91,
    status: "Discovered",
  },
  {
    id: "8",
    name: "Amara Okafor",
    jobTitle: "VP of Strategic Alliances",
    role: "Executive",
    company: "SaaSBridge Global",
    industry: "Cloud Infrastructure",
    companySize: "500-1000",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    location: "Toronto, ON, Canada",
    email: "amara.o@saasbridge.com",
    verificationTag: "Email verified",
    matchReason: "Scaling ecosystem partnerships with enterprise SaaS buyers.",
    matchScore: 89,
    status: "Discovered",
  },
  {
    id: "9",
    name: "Marcus Vance",
    jobTitle: "Managing Director, Commercial",
    role: "Executive",
    company: "Vanguard Growth Partners",
    industry: "Marketing & Agency",
    companySize: "250-500",
    country: "United States",
    state: "New York",
    city: "New York",
    location: "New York, NY, USA",
    email: "m.vance@vanguardgp.com",
    verificationTag: "Review contact",
    matchReason: "Commercial agency leader actively hiring outbound sales SDRs.",
    matchScore: 88,
    status: "Discovered",
  },
  {
    id: "10",
    name: "Sophie Leclerc",
    jobTitle: "VP Revenue Operations",
    role: "Executive",
    company: "Luminary AI",
    industry: "Enterprise SaaS",
    companySize: "100-250",
    country: "United States",
    state: "California",
    city: "San Francisco",
    location: "San Francisco, CA, USA",
    email: "sleclerc@luminaryai.com",
    verificationTag: "Email verified",
    matchReason: "Focusing on sales inbox deliverability and deliverability guards.",
    matchScore: 97,
    status: "Discovered",
  },
];

export function leadDomain(lead: Lead) {
  return lead.domain || lead.email.split("@")[1] || "";
}

export function uniqueSorted(values: string[]) {
  return Array.from(new Set(values.filter(Boolean))).sort((a, b) => a.localeCompare(b));
}
