import { Lead, Campaign, EmailThread, Meeting } from '../types';

export type SetupLead = Lead & { setupIndustry: "Agency" | "SaaS" | "Recruiting" };

export const campaignSetupLeads: SetupLead[] = [
  {
    id: "1",
    name: "Melissa Grant",
    jobTitle: "Growth Director",
    role: "Director",
    company: "Aster & Co.",
    industry: "Marketing & Agency",
    setupIndustry: "Agency",
    companySize: "50-100",
    country: "United Kingdom",
    state: "Greater London",
    city: "London",
    location: "London, UK",
    email: "m.grant@asterco.co.uk",
    verificationTag: "Email verified",
    matchReason: "Agency growth leader with a relevant expansion signal.",
    matchScore: 98,
  },
  {
    id: "2",
    name: "Omar Siddiqui",
    jobTitle: "Founder",
    role: "Executive",
    company: "Formstack Labs",
    industry: "Enterprise SaaS",
    setupIndustry: "SaaS",
    companySize: "100-250",
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    location: "Dubai, UAE",
    email: "omar@formstacklabs.io",
    verificationTag: "Enriched",
    matchReason: "Founder-led B2B team actively building a repeatable pipeline.",
    matchScore: 96,
  },
  {
    id: "3",
    name: "Sana Ahmed",
    jobTitle: "Managing Partner",
    role: "Executive",
    company: "Northstar Talent",
    industry: "Staffing & Recruiting",
    setupIndustry: "Recruiting",
    companySize: "10-50",
    country: "Pakistan",
    state: "Sindh",
    city: "Karachi",
    location: "Karachi, PK",
    email: "sana@northstartalent.com",
    verificationTag: "Email verified",
    matchReason: "Recruitment decision-maker with high-fit service motion.",
    matchScore: 94,
  },
  {
    id: "4",
    name: "James Chen",
    jobTitle: "Head of Partnerships",
    role: "Director",
    company: "Kindred Studio",
    industry: "Marketing & Agency",
    setupIndustry: "Agency",
    companySize: "50-100",
    country: "Singapore",
    state: "Central Region",
    city: "Singapore",
    location: "Singapore",
    email: "james.chen@kindredstudio.sg",
    verificationTag: "Review contact",
    matchReason: "Partnership remit aligns with expansion and pipeline goals.",
    matchScore: 92,
  },
];

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Melissa Grant',
    jobTitle: 'Growth Director',
    role: 'Director',
    company: 'Aster & Co.',
    industry: 'Marketing & Agency',
    companySize: '50-100',
    country: 'United Kingdom',
    state: 'Greater London',
    city: 'London',
    location: 'London, UK',
    email: 'm.grant@asterco.co.uk',
    verificationTag: 'Email verified',
    matchReason: 'Agency growth leader with a relevant expansion signal.',
    matchScore: 98,
    status: 'Replied',
  },
  {
    id: '2',
    name: 'Omar Siddiqui',
    jobTitle: 'Founder & CEO',
    role: 'Executive',
    company: 'Formstack Labs',
    industry: 'Enterprise SaaS',
    companySize: '100-250',
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    location: 'Dubai, UAE',
    email: 'omar@formstacklabs.io',
    verificationTag: 'Enriched',
    matchReason: 'Founder-led team seeking qualified sales conversations.',
    matchScore: 96,
    status: 'Meeting Booked',
  },
  {
    id: '3',
    name: 'Sana Ahmed',
    jobTitle: 'Managing Partner',
    role: 'Executive',
    company: 'Northstar Talent',
    industry: 'Staffing & Recruiting',
    companySize: '10-50',
    country: 'Pakistan',
    state: 'Sindh',
    city: 'Karachi',
    location: 'Karachi, PK',
    email: 'sana@northstartalent.com',
    verificationTag: 'Email verified',
    matchReason: 'Recruitment decision-maker with high-fit service motion.',
    matchScore: 94,
    status: 'Contacted',
  },
  {
    id: '4',
    name: 'James Chen',
    jobTitle: 'Head of Partnerships',
    role: 'Director',
    company: 'Kindred Studio',
    industry: 'Marketing & Agency',
    companySize: '50-100',
    country: 'Singapore',
    state: 'Central Region',
    city: 'Singapore',
    location: 'Singapore',
    email: 'james.chen@kindredstudio.sg',
    verificationTag: 'Review contact',
    matchReason: 'Partnership remit aligns with expansion and pipeline goals.',
    matchScore: 92,
    status: 'Discovered',
  },
  {
    id: '5',
    name: 'Sarah Jenkins',
    jobTitle: 'VP of Demand Generation',
    role: 'Executive',
    company: 'CloudScale Inc.',
    industry: 'Enterprise SaaS',
    companySize: '250-500',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    location: 'San Francisco, CA, USA',
    email: 's.jenkins@cloudscale.io',
    verificationTag: 'Email verified',
    matchReason: 'Scaling outbound revenue with deliverability safeguards.',
    matchScore: 95,
    status: 'Replied',
  },
  {
    id: '6',
    name: 'Elena Rostova',
    jobTitle: 'Head of Sales Operations',
    role: 'Director',
    company: 'Nexlify Bio',
    industry: 'Healthcare Technology',
    companySize: '100-250',
    country: 'Germany',
    state: 'Berlin',
    city: 'Berlin',
    location: 'Berlin, Germany',
    email: 'elena@nexlifybio.de',
    verificationTag: 'Enriched',
    matchReason: 'Leading revenue operations and automated lead workflows.',
    matchScore: 90,
    status: 'Contacted',
  },
  {
    id: '7',
    name: 'David K. Chen',
    jobTitle: 'Director of Growth Marketing',
    role: 'Director',
    company: 'ApexLogistics AI',
    industry: 'Supply Chain AI',
    companySize: '100-250',
    country: 'United States',
    state: 'Texas',
    city: 'Austin',
    location: 'Austin, TX, USA',
    email: 'dchen@apexlogistics.ai',
    verificationTag: 'Email verified',
    matchReason: 'Director evaluating deliverability and automated prospecting.',
    matchScore: 91,
    status: 'Discovered',
  },
  {
    id: '8',
    name: 'Amara Okafor',
    jobTitle: 'VP of Strategic Alliances',
    role: 'Executive',
    company: 'SaaSBridge Global',
    industry: 'Cloud Infrastructure',
    companySize: '500-1000',
    country: 'Canada',
    state: 'Ontario',
    city: 'Toronto',
    location: 'Toronto, ON, Canada',
    email: 'amara.o@saasbridge.com',
    verificationTag: 'Email verified',
    matchReason: 'Scaling ecosystem partnerships with enterprise SaaS buyers.',
    matchScore: 89,
    status: 'Replied',
  },
  {
    id: '9',
    name: 'Marcus Vance',
    jobTitle: 'Managing Director, Commercial',
    role: 'Executive',
    company: 'Vanguard Growth Partners',
    industry: 'Marketing & Agency',
    companySize: '250-500',
    country: 'United States',
    state: 'New York',
    city: 'New York',
    location: 'New York, NY, USA',
    email: 'm.vance@vanguardgp.com',
    verificationTag: 'Review contact',
    matchReason: 'Commercial agency leader actively hiring outbound sales SDRs.',
    matchScore: 88,
    status: 'Discovered',
  },
  {
    id: '10',
    name: 'Sophie Leclerc',
    jobTitle: 'VP Revenue Operations',
    role: 'Executive',
    company: 'Luminary AI',
    industry: 'Enterprise SaaS',
    companySize: '100-250',
    country: 'United States',
    state: 'California',
    city: 'San Francisco',
    location: 'San Francisco, CA, USA',
    email: 'sleclerc@luminaryai.com',
    verificationTag: 'Email verified',
    matchReason: 'Focusing on sales inbox deliverability and deliverability guards.',
    matchScore: 97,
    status: 'Replied',
  },
];

export const locationSuggestions = [
  'London, UK',
  'Dubai, UAE',
  'Karachi, PK',
  'Singapore',
  'San Francisco, CA, USA',
  'Berlin, Germany',
  'Austin, TX, USA',
  'Toronto, ON, Canada',
  'New York, NY, USA',
  'Paris, France',
  'Dublin, Ireland',
  'Sydney, Australia',
];

export interface StateLocation {
  name: string;
  cities: string[];
}

export interface CountryLocation {
  country: string;
  states: StateLocation[];
}

export const mockLocations: CountryLocation[] = [
  {
    country: 'United Kingdom',
    states: [
      { name: 'Greater London', cities: ['London'] },
      { name: 'Manchester', cities: ['Manchester'] },
      { name: 'West Midlands', cities: ['Birmingham'] },
    ],
  },
  {
    country: 'United States',
    states: [
      { name: 'California', cities: ['San Francisco', 'Los Angeles', 'San Diego'] },
      { name: 'Texas', cities: ['Austin', 'Dallas', 'Houston'] },
      { name: 'New York', cities: ['New York', 'Buffalo'] },
      { name: 'Florida', cities: ['Miami', 'Orlando'] },
    ],
  },
  {
    country: 'United Arab Emirates',
    states: [
      { name: 'Dubai', cities: ['Dubai'] },
      { name: 'Abu Dhabi', cities: ['Abu Dhabi'] },
    ],
  },
  {
    country: 'Pakistan',
    states: [
      { name: 'Sindh', cities: ['Karachi'] },
      { name: 'Punjab', cities: ['Lahore', 'Islamabad'] },
    ],
  },
  {
    country: 'Singapore',
    states: [
      { name: 'Central Region', cities: ['Singapore'] },
    ],
  },
  {
    country: 'Germany',
    states: [
      { name: 'Berlin', cities: ['Berlin'] },
      { name: 'Bavaria', cities: ['Munich'] },
    ],
  },
  {
    country: 'Canada',
    states: [
      { name: 'Ontario', cities: ['Toronto', 'Ottawa'] },
      { name: 'British Columbia', cities: ['Vancouver'] },
    ],
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Q4 Agency Pipeline',
    brief: 'We help boutique recruitment firms book more qualified client conversations with deliverability safeguards.',
    status: 'Draft saved',
    leadsCount: 1200,
    sentCount: 0,
    replyRate: 0,
    sequence: [
      {
        step: 1,
        delayDays: 0,
        subject: 'Quick question regarding {{company}} client pipeline',
        body: 'Hi {{first_name}},\n\nNoticed {{company}}\'s growth in tech recruitment. We help recruitment leaders book 20+ qualified enterprise client meetings each month.\n\nWorth a brief 7-minute intro this Thursday?',
      },
      {
        step: 2,
        delayDays: 3,
        subject: 'Re: Quick question regarding {{company}} client pipeline',
        body: 'Hi {{first_name}},\n\nFollowing up on my note earlier. Thought you might find our case study helpful on how similar firms cut SDR prospecting time in half.\n\nOpen to seeing a quick 30-second breakdown?',
      },
    ],
  },
  {
    id: 'camp-2',
    name: 'Enterprise SaaS RevOps',
    brief: 'Targeting RevOps Directors in B2B Software looking to protect domain health and inbox deliverability.',
    status: 'Live',
    leadsCount: 450,
    sentCount: 280,
    replyRate: 18.5,
    sequence: [
      {
        step: 1,
        delayDays: 0,
        subject: 'Protecting {{company}} outbound deliverability',
        body: 'Hello {{first_name}},\n\nReaching out because {{company}} is scaling sales outbound. LeadLens enforces automated warmup and progressive lead verification so your team stays out of spam.',
      },
    ],
  },
];

export const mockThreads: EmailThread[] = [
  {
    id: 'thr-1',
    leadName: 'Melissa Grant',
    leadTitle: 'Growth Director',
    company: 'Aster & Co.',
    email: 'm.grant@asterco.co.uk',
    subject: 'Re: Quick question regarding Aster & Co. client pipeline',
    category: 'Interested',
    timestamp: '15 mins ago',
    preview: 'Hey Alex, good timing. We are actually looking to expand our outbound stack for next month. Can you share a quick link to book 15 mins?',
    messages: [
      {
        sender: 'user',
        senderName: 'Alex Morgan',
        time: 'Yesterday at 10:15 AM',
        content: 'Hi Melissa, noticed Aster & Co.\'s expansion. We help agency leaders book qualified conversations with safeguard-first routing. Worth a brief 7-minute intro this Thursday?',
      },
      {
        sender: 'lead',
        senderName: 'Melissa Grant',
        time: '15 mins ago',
        content: 'Hey Alex, good timing. We are actually looking to expand our outbound stack for next month. Can you share a quick link to book 15 mins?',
      },
    ],
  },
  {
    id: 'thr-2',
    leadName: 'Omar Siddiqui',
    leadTitle: 'Founder',
    company: 'Formstack Labs',
    email: 'omar@formstacklabs.io',
    subject: 'Re: Scaling sales conversations',
    category: 'Needs Info',
    timestamp: '2 hours ago',
    preview: 'Does LeadLens integrate directly with Google Workspace and HubSpot, or do we export CSVs?',
    messages: [
      {
        sender: 'user',
        senderName: 'Alex Morgan',
        time: 'Sep 19 at 2:30 PM',
        content: 'Hi Omar, saw your expansion. Open to a brief exchange on outbound deliverability?',
      },
      {
        sender: 'lead',
        senderName: 'Omar Siddiqui',
        time: '2 hours ago',
        content: 'Does LeadLens integrate directly with Google Workspace and HubSpot, or do we export CSVs?',
      },
    ],
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: 'meet-1',
    leadName: 'Melissa Grant',
    company: 'Aster & Co.',
    jobTitle: 'Growth Director',
    date: 'Friday, Sept 25, 2026',
    time: '10:00 AM - 10:30 AM BST',
    status: 'Confirmed',
  },
  {
    id: 'meet-2',
    leadName: 'Omar Siddiqui',
    company: 'Formstack Labs',
    jobTitle: 'Founder',
    date: 'Monday, Sept 28, 2026',
    time: '2:00 PM - 2:30 PM GST',
    status: 'Confirmed',
  },
];
